### ISSUE TITLE
Can you point links to update countries.json

### ISSUE THREAD

**Issue by pavan2you** [uglymittens/country-master#4]
Hi Victor, 

Your library helped but wondering how to keep latest countries.json and countrylatlan.json? Can you point from where you got them?

thanks
Pavan

**Comment by uglymittens** [comment]
I had compiled the list from this Wikipedia page: https://en.wikipedia.org/wiki/Country_code

Sometime after I had created the list, Wikipedia had changed the format, making it harder to scrape the data. 

As far as "countrylatlan.json", I don't believe that this is in the library. Are you looking to build a list of country latitude and longitude?

Hope this helps!

**Comment by pavan2you** [comment]
Oh ok..

'countrylatlan.json' I might have copied it from some other place.

Thanks Victor.

-Pavan

**Comment by uglymittens** [comment]
No problems Pavan 👍
